### ISSUE TITLE
What does this repo do?

### ISSUE THREAD

**Issue by rotu** [moonrepo/schema-plugin#8]
It's not clear what this plugin does or what tools it exists to support.

The description is:
> WASM plugin for [proto](https://github.com/moonrepo/proto) that is powered by a schema. Currently supports TOML.

It seems like this might be the plugin described elsewhere as ["the TOML plugin"](https://moonrepo.dev/docs/proto/toml-plugin), in which case the naming should be clarified and the readme should make clear that this is not to support a tool called "schema" but for defining new proto plugins declaratively.

**Comment by milesj** [comment]
This plugin is what powers the TOML plugins under the hood. Since proto is powered entirely by WASM, we can't simply execute TOML, so this plugin acts as a bridge that uses the TOML schema to power the WASM functions.

It's more of an implementation detail, but I can update the description.

**Comment by rotu** [comment]
> This plugin is what powers the TOML plugins under the hood

Perfect! I see you've updated it already :-).
